# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 02:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='navbars_blog',
            options={'verbose_name': '\u535a\u5ba2\u5bfc\u822a', 'verbose_name_plural': '\u535a\u5ba2\u5bfc\u822a'},
        ),
        migrations.AddField(
            model_name='article',
            name='top_img',
            field=models.ImageField(blank=True, null=True, upload_to='blog_img/%Y/%m.%d', verbose_name='\u535a\u5ba2\u9996\u56fe\u7247'),
        ),
    ]
