# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 02:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0002_auto_20170727_1025'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='desc',
            field=models.CharField(max_length=150, verbose_name='\u6587\u7ae0\u63cf\u8ff0'),
        ),
    ]
