# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 08:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app_blog', '0003_auto_20170727_1055'),
    ]

    operations = [
        migrations.CreateModel(
            name='Picture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u624b\u673a\u540d\u5b57')),
                ('img_url', models.ImageField(upload_to='uploads/', verbose_name='\u624b\u673a\u56fe\u7247')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_blog.Category', verbose_name='\u5206\u7c7b')),
            ],
            options={
                'verbose_name': '\u4ea7\u54c1\u56fe\u7247',
                'verbose_name_plural': '\u4ea7\u54c1\u56fe\u7247',
            },
        ),
        migrations.CreateModel(
            name='Picture2',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='\u624b\u673a\u540d\u5b57')),
                ('phone', models.CharField(max_length=500, verbose_name='\u624b\u673a\u63cf\u8ff0')),
                ('img2_url', models.ImageField(upload_to='uploads/', verbose_name='\u624b\u673a\u56fe\u72472')),
                ('content', models.TextField(verbose_name='\u56fe\u7247\u4e0b\u8f7d')),
                ('Picture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_blog.Picture', verbose_name='\u4ea7\u54c1\u56fe\u72471')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app_blog.Category', verbose_name='\u5206\u7c7b')),
            ],
            options={
                'verbose_name': '\u4ea7\u54c1\u56fe\u72472',
                'verbose_name_plural': '\u4ea7\u54c1\u56fe\u72472',
            },
        ),
        migrations.CreateModel(
            name='Series',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='\u7cfb\u5217\u6807\u9898')),
            ],
            options={
                'verbose_name': '\u4ea7\u54c1\u7cfb\u5217',
                'verbose_name_plural': '\u4ea7\u54c1\u7cfb\u5217',
            },
        ),
        migrations.AddField(
            model_name='picture2',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_blog.Series', verbose_name='\u7cfb\u5217'),
        ),
        migrations.AddField(
            model_name='picture2',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237'),
        ),
        migrations.AddField(
            model_name='picture',
            name='series',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_blog.Series', verbose_name='\u7cfb\u5217'),
        ),
        migrations.AddField(
            model_name='picture',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='\u7528\u6237'),
        ),
    ]
