# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 08:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0004_auto_20170731_1610'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='picture',
            name='user',
        ),
        migrations.RemoveField(
            model_name='picture2',
            name='user',
        ),
    ]
