# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0005_auto_20170731_1625'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='username',
            field=models.CharField(blank=True, max_length=30, null=True, verbose_name='\u8bc4\u8bba\u7528\u6237\u540d'),
        ),
    ]
