# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-01 06:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_blog', '0006_comment_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('img_url', models.ImageField(blank=True, upload_to='blog/video/%Y/%m')),
                ('video_url', models.CharField(max_length=200, verbose_name='\u89c6\u9891\u8d44\u6e90URL')),
                ('video_length', models.IntegerField(verbose_name='\u89c6\u9891\u957f\u5ea6')),
            ],
            options={
                'verbose_name': '\u89c6\u9891',
                'verbose_name_plural': '\u89c6\u9891',
            },
        ),
    ]
