# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_desc',
            name='img_url',
            field=models.ImageField(blank=True, upload_to=b'shop/product_desc/%Y/%m'),
        ),
    ]
