# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-12 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_store', '0002_auto_20170812_1418'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_details',
            name='img_url',
        ),
        migrations.AddField(
            model_name='product_details',
            name='img_url1',
            field=models.ImageField(blank=True, upload_to=b'shop/product/%Y/%m'),
        ),
        migrations.AddField(
            model_name='product_details',
            name='img_url2',
            field=models.ImageField(blank=True, upload_to=b'shop/product/%Y/%m'),
        ),
        migrations.AddField(
            model_name='product_details',
            name='img_url3',
            field=models.ImageField(blank=True, upload_to=b'shop/product/%Y/%m'),
        ),
        migrations.AddField(
            model_name='product_details',
            name='img_url4',
            field=models.ImageField(blank=True, upload_to=b'shop/product/%Y/%m'),
        ),
        migrations.AlterField(
            model_name='product_details',
            name='title',
            field=models.CharField(blank=True, max_length=30, verbose_name=b'\xe6\xa0\x87\xe9\xa2\x98'),
        ),
    ]
